# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-19 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes about the author'),
            preserve_default=False,
        ),
    ]
